### ISSUE TITLE
Supporting Rails 5

### ISSUE THREAD

**Issue by benlovell** [alphagov/gds-sso#103]
As I mentioned privately to @boffbowsh -- I'm a good way along with making this gem Rails 5 compatible and am keen to keep our changes going upstream.

One outstanding issue is Rails 5 dropping support for Rubies earlier than 2.2.2, thanks to Rack 2's requirements.

I couldn't remember if you folks still maintain projects targeting earlier rubies so perhaps this is a non-issue? If you do, we could still maintain backwards compatibility for those older Ruby / Rails versions but would likely suffer a wall of deprecation messages when running in the context of Rails 5.x. There are of course workarounds we could employ -- checking the Rails version at runtime and doing the Right Thing:tm:.

Happy to take a steer on your most favoured approach. Thoughts?

**Comment by boffbowsh** [comment]
Yo. Cheers for helping out on this. We're actively working towards getting rid of Ruby 2.1 on our apps, so making gds-sso support 2.2+ only is fine. If apps need to upgrade to a newer gds-sso, they can upgrade Ruby at the same time. 

Almost everything is now on Rails 4.2+ so you wouldn't need to worry about incompatibility with older Railses.

Cheers again, shout via the various internet methods if you need a hand with anything.

**Comment by benlovell** [comment]
Perfect, thanks ❤️💛💚💙
