### ISSUE TITLE
Determining "API" calls

### ISSUE THREAD

**Issue by benlovell** [alphagov/gds-sso#106]
The issue arises when an application calls back to itself via AJAX from the client - say to bind a UI element to a collection of JSON resources.

The user is authenticated, has a current session and the client library will pass the session cookie - so there is no need to authenticate via other means. However, the presence of the `HTTP_ACCEPT: application/json` header / value dictates the (gds-sso) hosting application will determine the call "API" in nature and will attempt to authenticate via a bearer-token that is not present. See:

```ruby
# lib/gds-sso/api_access.rb
require 'rack/accept'

module GDS
  module SSO
    class ApiAccess
      def self.api_call?(env)
        request = Rack::Accept::Request.new(env)
        request.best_media_type(%w{text/html application/json}) == 'application/json'
      end
    end
  end
end
```

I'm proposing an alteration to this behaviour so requests are considered "API" in nature - based only upon the presence of a bearer token. This would permit clients to make "API" calls in the context of the current user without needing further forms of authentication.

It seems from my rudimentary search in existing GDS apps that this would not be a breaking change, but I thought I'd float the idea before going ahead. Thoughts?

cc: @boffbowsh

**Comment by boffbowsh** [comment]
This makes sense to me. As long as it's a major version change of this gem, applications can then fix their behaviour if needed.
